package dev.doglog.internal.log_thread.entries;

/** The type of a queued log entry. */
public enum EntryType {
  BOOLEAN_ARRAY,
  BOOLEAN,

  DOUBLE_ARRAY,
  DOUBLE,
  DOUBLE_ARRAY_WITH_UNIT,
  DOUBLE_WITH_UNIT,

  FLOAT_ARRAY,
  FLOAT,
  FLOAT_ARRAY_WITH_UNIT,
  FLOAT_WITH_UNIT,

  INTEGER_ARRAY,
  INTEGER,
  INTEGER_ARRAY_WITH_UNIT,
  INTEGER_WITH_UNIT,

  STRING_ARRAY,
  STRING,
  STRING_CUSTOM_TYPE,

  STRUCT_ARRAY,
  STRUCT,
}
