import markdoc from '@astrojs/markdoc';
import starlight from '@astrojs/starlight';
import AstroPWA from '@vite-pwa/astro';
import { defineConfig } from 'astro/config';
import fs from 'fs/promises';
import path from 'path';

// https://astro.build/config
export default defineConfig({
	site: 'https://2027.doglog.dev',
	trailingSlash: 'never',
	integrations: [
		{
			name: 'copy-files',
			hooks: {
				'astro:config:setup': async () => {
					await Promise.all([writeChangelogToContent(), copyVendordep()]);
				},
			},
		},
		starlight({
			title: 'DogLog Docs',
			favicon: '/favicon.ico',
			social: [
				{
					href: 'https://github.com/jonahsnider/doglog',
					icon: 'github',
					label: 'GitHub',
				},
			],
			logo: {
				alt: 'DogLog logo',
				src: './public/logo.svg',
			},
			sidebar: [
				{
					label: 'Getting started',
					autogenerate: { directory: 'getting-started' },
				},
				{
					label: 'Guides',
					autogenerate: { directory: 'guides' },
				},
				{
					label: 'Reference',
					autogenerate: { directory: 'reference' },
				},
				{
					label: 'Javadoc',
					link: 'https://javadoc.doglog.dev',
				},
			],
			customCss: ['/src/styles/custom.css'],
			components: {
				Head: './src/components/PwaHead.astro',
			},
		}),
		markdoc(),
		AstroPWA({
			base: '/',
			scope: '/',
			registerType: 'autoUpdate',
			workbox: {
				cleanupOutdatedCaches: true,
				cacheId: 'doglog-docs',
				globPatterns: ['**/*'],
			},
			manifest: {
				name: 'DogLog Docs',
				short_name: 'DogLog',
				background_color: '#ffffff',
				description: 'Simpler logging for FRC, DogLog is the easiest way to add logging to your robot code',
				theme_color: '#460b05',
				lang: 'en',
				display: 'minimal-ui',
				id: 'doglog.dev',
				start_url: '/',
				orientation: 'any',
			},
			pwaAssets: {
				image: './public/logo.svg',
			},
			experimental: {
				directoryAndTrailingSlashHandler: true,
			},
		}),
	],
	redirects: {
		'/guides/faults': '/reference/faults',
		'/guides/tunable-values': '/reference/tunable-values',
	},
});

async function writeChangelogToContent() {
	const CHANGELOG_INPUT_PATH = path.join(import.meta.dirname, '..', 'CHANGELOG.md');
	const OUTPUT_PATH = path.join(import.meta.dirname, 'src', 'content', 'docs', 'reference', 'changelog.md');

	const rawChangelog = await fs.readFile(CHANGELOG_INPUT_PATH, 'utf-8');

	const newChangelog =
		[
			'---',
			'# AUTOGENERATED - see astro.config.mjs',
			'title: Changelog',
			'description: Changelog of updates to DogLog.',
			'---',
			'',
		].join('\n') + rawChangelog.replace('# Changelog', '');

	await fs.writeFile(OUTPUT_PATH, newChangelog);
}

async function copyVendordep() {
	const VENDORDEP_INPUT_PATH = path.join(import.meta.dirname, '..', 'vendordep.json');
	const OUTPUT_PATH = path.join(import.meta.dirname, 'public', 'vendordep.json');

	await fs.copyFile(VENDORDEP_INPUT_PATH, OUTPUT_PATH);
}
