import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLinksValidator from 'starlight-links-validator';
import fs from 'fs/promises';
import path from 'path';

// https://astro.build/config
export default defineConfig({
	site: 'https://doglog.dev',
	vite: {
		resolve: {
      // The vendordep.json file is symlinked, Vite can't resolve it unless this is set
			preserveSymlinks: true,
		},
	},
	integrations: [
		{
			name: 'copy-changelog',
			hooks: {
				'astro:config:setup': async () => {
					await writeChangelogToContent();
				},
			},
		},
		starlight({
			plugins: [starlightLinksValidator()],
			title: 'DogLog Docs',
			favicon: '/favicon.ico',
			social: {
				github: 'https://github.com/jonahsnider/doglog',
			},
			logo: {
				alt: 'DogLog logo',
				src: './src/assets/logo.svg',
			},
			sidebar: [
				{
					label: 'Getting started',
					autogenerate: { directory: 'getting-started' },
				},
				{
					label: 'Guides',
					autogenerate: { directory: 'guides' },
				},
				{
					label: 'Reference',
					autogenerate: { directory: 'reference' },
				},
				{
					label: 'Javadoc',
					link: 'https://javadoc.doglog.dev',
				},
			],
			customCss: ['/src/styles/custom.css'],
		}),
	],
});

async function writeChangelogToContent() {
	const CHANGELOG_INPUT_PATH = path.join(import.meta.dirname, '..', 'CHANGELOG.md');
	const OUTPUT_PATH = path.join(import.meta.dirname, 'src', 'content', 'docs', 'reference', 'changelog.md');

	const rawChangelog = await fs.readFile(CHANGELOG_INPUT_PATH, 'utf-8');

	const newChangelog =
		[
			'---',
			'# AUTOGENERATED - see astro.config.mjs',
			'title: Changelog',
			'description: Changelog of updates to DogLog.',
			'---',
			'',
		].join('\n') + rawChangelog.replace('# Changelog', '');

	await fs.writeFile(OUTPUT_PATH, newChangelog);
}
